models:
  - type: content_safety_quick
    engine: openai
    parameters:
      openai_api_base: http://localhost:12434/v1
      model_name: huggingface.co/mradermacher/qwen3guard-gen-4b-gguf:Q8_0
      openai_api_key: "not-used"
      temperature: 0.0

rails:
  input:
    flows:
      - content safety check input $model=content_safety_quick
  output:
    flows:
      - content safety check output $model=content_safety_quick
  configs:
    content_safety:
      multilingual:
        enabled : true
        refusal_messages:
          zh: "抱歉，这个问题我无法回答，换个问题试试吧。"