rails:
  config:
    injection_detection:
      injections:
        - template
      action:
        reject

  input:
    flows:
      - injection_detection

  output:
    flows:
      - injection detection