models:
  - type: main
    engine: ollama
    model: qwen3:30b-instruct

rails:
  input:
    flows:
      - self check input

  output:
    flows:
      - self check output

  # dialog:
  #   # Whether to try to use a single LLM call for generating the user intent, next step and bot message.
  #   single_call:
  #     enabled: True

  #     # If a single call fails, whether to fall back to multiple LLM calls.
  #     fallback_to_multiple_calls: True


