models:
  - type: content_safety_reasoning
    engine: openai
    parameters:
      openai_api_base: "http://localhost:12434/v1"
      model_name: "huggingface.co/unsloth/gpt-oss-safeguard-20b-gguf:Q8_0"
      openai_api_key: "not-used"

rails:
  input:
    flows:
      - content safety check input $model=content_safety_reasoning
  output:
    flows:
      - content safety check output $model=content_safety_reasoning
  configs:
    content_safety:
      reasoning:
        enabled: true
      multilingual:
        enabled : true
        refusal_messages:
          zh: "抱歉，这个问题我无法回答，换个问题试试吧。"